### ISSUE TITLE
Public Chat

### ISSUE THREAD

**Issue by hamadmarri** [hamadmarri/cacule-cpu-scheduler#21]
Hi Everyone

Consider this as an open thread to discuss and talk about Cachy/CacULE

I would post some patches for testing too.

We could talk about how to enhance the scheduler. 

Thank you.

**Comment by hamadmarri** [comment]
Please try the global runqueue balancer patch on top of cacule

https://github.com/hamadmarri/cacule-cpu-scheduler/blob/master/patches/CacULE/v5.9/02-grq-5.9.patch

Let me know if there is any errors on kernel log, and any performance improvements.

Thank you

**Comment by raykzhao** [comment]
Hi @hamadmarri 

I got some page table or page map errors in dmesg with the grq patch. Sometimes the app or even the whole system will freeze. Also just after a system freeze, I need to run e2fsck in order to fix the filesystem corruption.
[log.txt](https://github.com/hamadmarri/cacule-cpu-scheduler/files/5746440/log.txt)

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> 
> I got some page table or page map errors in dmesg with the grq patch. Sometimes the app or even the whole system will freeze. Also just after a system freeze, I need to run e2fsck in order to fix the filesystem corruption.
> [log.txt](https://github.com/hamadmarri/cacule-cpu-scheduler/files/5746440/log.txt)

Yes, that was a problem but I thought I fixed it with the last commit c7bbf9c3f617bf5c37ce8b45ef4c99076051cc96. Which commit you tried?

**Comment by raykzhao** [comment]
Hi @hamadmarri 

I believe I used the latest patch when I reported the bug, which should include the fix you mentioned. 

The out-of-tree kernel patches I'm using are here: https://gitlab.com/raykzhao/raykzhao-overlay/-/tree/master/sys-kernel/ray-cacule-sources/files. Also my kernel config should only have minor differences compared with the attachment i.e. replacing Cachy with CacULE. 

[config-5.10.3.zip](https://github.com/hamadmarri/cacule-cpu-scheduler/files/5746970/config-5.10.3.zip)

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> 
> I believe I used the latest patch when I reported the bug, which should include the fix you mentioned.
> 
> The out-of-tree kernel patches I'm using are here: https://gitlab.com/raykzhao/raykzhao-overlay/-/tree/master/sys-kernel/ray-cacule-sources/files. Also my kernel config should only have minor differences compared with the attachment i.e. replacing Cachy with CacULE.
> 
> [config-5.10.3.zip](https://github.com/hamadmarri/cacule-cpu-scheduler/files/5746970/config-5.10.3.zip)

Hi @raykzhao 

I am compiling it with `CONFIG_PREEMPT=y`, it could be a reason. I have test the https://github.com/hamadmarri/cacule-cpu-scheduler/commit/c7bbf9c3f617bf5c37ce8b45ef4c99076051cc96 with `CONFIG_PREEMPT_VOLUNTARY` for about 24h with no error appeared. Usually (before the last commit), the error happens in random times but within few hours. 

Just for the sake of cariousity, I noticed that you are using HZ=100 and CONFIG_PREEMPT, I know 100hz increase the performance but with less interactivity. Would setting CONFIG_PREEMPT with 100hz helps to overcome latency issues but maintaining performance?

Thank you

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> 
> I believe I used the latest patch when I reported the bug, which should include the fix you mentioned.
> 
> The out-of-tree kernel patches I'm using are here: https://gitlab.com/raykzhao/raykzhao-overlay/-/tree/master/sys-kernel/ray-cacule-sources/files. Also my kernel config should only have minor differences compared with the attachment i.e. replacing Cachy with CacULE.
> 
> [config-5.10.3.zip](https://github.com/hamadmarri/cacule-cpu-scheduler/files/5746970/config-5.10.3.zip)

Hi @raykzhao 

I confirm this bug happens when `CONFIG_PREEMPT=y`. Could you please try with `CONFIG_PREEMPT_VOLUNTARY = y` until I fix the bug with CONFIG_PREEMPT

Please let me know if the bug still reported with `CONFIG_PREEMPT_VOLUNTARY = y`. In my machine no bug shown so far.

You might backup your files first :D

Thank you

**Comment by raykzhao** [comment]
Hi @hamadmarri 

Unfortunately I'm still getting app/system freeze even after switching to voluntary preemption. Other than that, the system is very smooth (even smoother than Cachy/CacULE) under heavy load. Remind me of the old BFS days when it was still using a global queue. 

[log.txt](https://github.com/hamadmarri/cacule-cpu-scheduler/files/5753196/log.txt)
[config-5.10.3-grq.zip](https://github.com/hamadmarri/cacule-cpu-scheduler/files/5753197/config-5.10.3-grq.zip)

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> 
> Unfortunately I'm still getting app/system freeze even after switching to voluntary preemption. Other than that, the system is very smooth (even smoother than Cachy/CacULE) under heavy load. Remind me of the old BFS days when it was still using a global queue.
> 
> [log.txt](https://github.com/hamadmarri/cacule-cpu-scheduler/files/5753196/log.txt)
> [config-5.10.3-grq.zip](https://github.com/hamadmarri/cacule-cpu-scheduler/files/5753197/config-5.10.3-grq.zip)

I removed grq from the hub since it harms the FS. I am thinking to borrow the bfs-ck and apply the hrrn on it. What do you think?

Thank you @raykzhao

**Comment by raykzhao** [comment]
Hi @hamadmarri 

Another (maybe more up-to-date) codebase might be the old VRQ scheduler (the predecessor of PDS) before it also switched to skiplist. It seems to be a variant of BFS by fixing some locking issues. However, I have no idea how it compared to BFS since I didn't know about it at that time. 

The latest VRQ scheduler I can find without skiplist is at http://cchalpha.blogspot.com/2016/08/v470472vrq3-patch-released.html. It is based on the 4.7.2 kernel source code.

**Comment by hamadmarri** [comment]
[grq-r2.zip](https://github.com/hamadmarri/cacule-cpu-scheduler/files/5758276/grq-r2.zip)

Please try this full patch. global locks moved to core.c with many locking (for every possible enqueue/dequeue paths). HRRN policy, so it is basically cachy with grq.

Thank you

**Comment by raykzhao** [comment]
Hi @hamadmarri 

I get the following compiling errors:

```
kernel/sched/core.c:7640:17: error: use of undeclared identifier 'p'
        GLOBAL_RQ_LOCK(p->sched_class);
                       ^
kernel/sched/core.c:7664:19: error: use of undeclared identifier 'p'
        GLOBAL_RQ_UNLOCK(p->sched_class);
```

Should they become `tsk->sched_class`?

By the way, does this patch work with `CONFIG_PREEMPT` now?

**Comment by raykzhao** [comment]
Hi @hamadmarri 

The new patch seems to work fine with `CONFIG_PREEMPT`, and I think #22 can be closed. The patch feels smoother than original Cachy and all variants of CacULE on my machine under heavy load. In fact, this seems to be the only scheduler that can play the video you posted at https://github.com/hamadmarri/cacule-cpu-scheduler/issues/15#issuecomment-748137399 at 1440p without any glitches when compiling the kernel with `make -j5` on my 4-core laptop. Cachy and all variants of CacULE on the other hand will have several glitches at 1440p in this case (all of them should be without glitches at 1080p though). 

However, it seems that the latency is slightly worse. I guess it's due to all the lockings. I will try to increase `CONFIG_HZ` and see if it will bring any improvement. In addition, I think you may cleanup the patch a bit, since I can see many codes are commented out. Also the `interactivity_factor` is unused and `cacule_max_lifetime` should be tunable via sysctl. 

Thank you very much for your work!

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> 
> I get the following compiling errors:
> 
> ```
> kernel/sched/core.c:7640:17: error: use of undeclared identifier 'p'
>         GLOBAL_RQ_LOCK(p->sched_class);
>                        ^
> kernel/sched/core.c:7664:19: error: use of undeclared identifier 'p'
>         GLOBAL_RQ_UNLOCK(p->sched_class);
> ```
> 
> Should they become `tsk->sched_class`?
> 
> By the way, does this patch work with `CONFIG_PREEMPT` now?

Hi @raykzhao 

I disabled CGROUP_SCHED since it is not needed, that's why it didn't show me an error. Sorry about that. Try disable CGROUP_SCHED it could enhance the performance.

I got crash when try to set the computer to sleep with no errors. Also I got NULL reference one time on reboot. I need to fix these issues. 

Thank you

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> 
> The new patch seems to work fine with `CONFIG_PREEMPT`, and I think #22 can be closed. The patch feels smoother than original Cachy and all variants of CacULE on my machine under heavy load. In fact, this seems to be the only scheduler that can play the video you posted at [#15 (comment)](https://github.com/hamadmarri/cacule-cpu-scheduler/issues/15#issuecomment-748137399) at 1440p without any glitches when compiling the kernel with `make -j5` on my 4-core laptop. Cachy and all variants of CacULE on the other hand will have several glitches at 1440p in this case (all of them should have no glitches at 1080p though).
> 
> However, it seems that the latency is slightly worse. I guess it's due to all the lockings. I will try to increase `CONFIG_HZ` and see if it will bring any improvement. Meanwhile I think you may cleanup the patch a bit, since I can see many codes are commented out. Also the `interactivity_factor` is unused and `cacule_max_lifetime` should be tunable via sysctl.
> 
> Thank you very much for your work!


>In fact, this seems to be the only scheduler that can play the video you posted at [#15 (comment)](https://github.com/hamadmarri/cacule-cpu-scheduler/issues/15#issuecomment-748137399) at 1440p without any glitches when compiling the kernel with `make -j5` on my 4-core laptop.

How about CFS, is grq better than CFS on this test?


>However, it seems that the latency is slightly worse.

Based on this test https://github.com/hamadmarri/os-scheduler-responsiveness-test, the results are no different than cachy. However, I am guessing that on some parts in the scheduler, the global lock discards some interrupts. I think I need to use `spin_lock_irqsave` instead of just `spin_lock` to save interrupts during waiting/spin to hold the lock.

I will clean up this patch soon.

Thank you

**Comment by raykzhao** [comment]
Hi @hamadmarri 

From what I read, `spin_lock` may cause deadlock when involving interrupts. I have encountered one system freeze so far (unfortunately the log didn't record anything useful), and I guess it could be possible due to a deadlock. 

I have replaced `spin_lock` with `spin_lock_irqsave` on my local kernel source as you suggested (and replacing `spin_unlock` with `spin_unlock_irqrestore`). So far I haven't encountered any system freeze yet.

**Comment by raykzhao** [comment]
> How about CFS, is grq better than CFS on this test?

Well, CFS seems to be the worst in this test. There are glitches even for 1080p with CFS. For 1440p, the glitches will cause the video stuck for a couple of seconds. I'm using `CONFIG_HZ=100` and `CONFIG_SCHED_AUTOGROUP=y` for my CFS build. I guess probably `CONFIG_HZ=100` is too low for CFS, but I can get away with alternative schedulers when using low clock frequency.

**Comment by hamadmarri** [comment]
Hi @raykzhao 

Does the system goes suspend successfully? On my machine it crashes when I try to suspend/sleep

Thank you

**Comment by raykzhao** [comment]
Hi @hamadmarri 

Unfortunately my system also hung when trying to suspend. I didn't compile the kernel with hibernation so I didn't try sleep. 

I'm recompiling the kernel with `CONFIG_PM_DEBUG=y` and will see if there would be any debugging information left in the log when trying to suspend.

**Comment by raykzhao** [comment]
Hi @hamadmarri 

I tried the PM debugging based on https://github.com/spotify/linux/blob/master/Documentation/power/basic-pm-debugging.txt. My system hung at the "processors" test. Based on the following suggestion from the documentation, I also got a system hung when trying to take a CPU core offline.

> If the "processors" test fails, the disabling/enabling of nonboot CPUs does not
work (of course, this only may be an issue on SMP systems) and the problem
should be reported.  In that case you can also try to switch the nonboot CPUs
off and on using the /sys/devices/system/cpu/cpu*/online sysfs attributes and
see if that works.

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> 
> I tried the PM debugging based on https://www.kernel.org/doc/Documentation/power/basic-pm-debugging.txt. My system hung at the "processors" test. Based on the following suggestion from the documentation, I also got a system freeze when trying to take a CPU core offline.
> 
> > If the "processors" test fails, the disabling/enabling of nonboot CPUs does not
> > work (of course, this only may be an issue on SMP systems) and the problem
> > should be reported.  In that case you can also try to switch the nonboot CPUs
> > off and on using the /sys/devices/system/cpu/cpu*/online sysfs attributes and
> > see if that works.
> 
> I guess it might needs to lock in the `__pick_migrate_task` function. I will try on my local kernel source.

Hi @raykzhao 

Please see the attached patch r3. I did some enhancements to cover less code during locks. Also I added a lock in __pick_migrate_task but didn't work too with suspend. 

[grq-r3.zip](https://github.com/hamadmarri/cacule-cpu-scheduler/files/5760071/grq-r3.zip)

**Comment by hamadmarri** [comment]
And this the full patch
[grq-r3.zip](https://github.com/hamadmarri/cacule-cpu-scheduler/files/5760079/grq-r3.zip)

**Comment by raykzhao** [comment]
Hi @hamadmarri 

I occasionally get system freeze. To be safe I would still turn every added lock to `spin_lock_irqsave` on my local kernel source.

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> 
> I occasionally get system freeze. To be safe I would still turn every lock to `spin_lock_irqsave` on my local kernel source for now.

Hi @raykzhao 

Could you please share your changes? When I added irqsave for every lock I got some kernel bug errors.

Thank you

**Comment by hf29h8sh321** [comment]
Hi,
I compiled with commit aba0dea93cbfed48092f04a4e6522abc83d17fe5 from kernel tree. I get stutters when system load spikes. For example, if I am working on some code, and frequently re-compile the code, any sound playing in the background will interrupt for around ~200ms, every time the compiler is invoked.

**Comment by raykzhao** [comment]
Hi @hf29h8sh321 

Please try the fix at https://github.com/hamadmarri/cacule-cpu-scheduler/issues/20#issuecomment-752214217.

**Comment by hamadmarri** [comment]
> Hi,
> I compiled with commit aba0dea93cbfed48092f04a4e6522abc83d17fe5 from kernel tree. I get stutters when system load spikes. For example, if I am working on some code, and frequently re-compile the code, any sound playing in the background will interrupt for around ~200ms, every time the compiler is invoked.

Hi @hf29h8sh321 

Sorry I forgot to push changes on github. I have just pushed changes.
Please try the last commit https://github.com/hamadmarri/linux/commit/21aa57c51799fd45189fe47caa30ea1eaa928515

Thank you

**Comment by hamadmarri** [comment]
[rdb-r1.zip](https://github.com/hamadmarri/cacule-cpu-scheduler/files/5762067/rdb-r1.zip)

Please try this. If performing better, I might consider it as the main patch.

It is cachy-r8 + rdb (response driven balancer)
It is stable since it uses regular multi-runqueues locking approach. Removed all load statistics for the load balancer since rdb uses HRRN values to migrate tasks.

Thanks

**Comment by raykzhao** [comment]
Hi @hamadmarri 

The rdb patch feels smoother than original Cachy/CacULE, but slightly worse than the grq patch under heavy load.

**Comment by hf29h8sh321** [comment]
Applying the patch from interactivity_score_fix.zip is not as smooth. If system is loaded, audio interrupts and ui feels laggy.

**Comment by raykzhao** [comment]
Hi @hamadmarri 

Just a minor bug in the rdb patch: the `cfs_rq_last_update_time` function should be removed when `CONFIG_CACHY_SCHED=y`. Currently the compiler will complain that `cfs_rq_last_update_time` doesn't have a return value on 32-bit devices.

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> 
> Just a minor bug in the rdb patch: the `cfs_rq_last_update_time` function should be removed when `CONFIG_CACHY_SCHED=y`. Currently the compiler will complain that `cfs_rq_last_update_time` doesn't have a return value on 32-bit devices. It's pretty safe to remove this function, since it's inline and its only caller `sync_entity_load_avg` is not used when `CONFIG_CACHY_SCHED=y` anyway.

Thank you @raykzhao I will clean it up :+1:

**Comment by hamadmarri** [comment]
Cachy with RDB balancer updated
https://github.com/hamadmarri/cacule-cpu-scheduler/blob/master/patches/Cachy/v5.9/cachy-5.9-r9.patch

**Comment by hamadmarri** [comment]
> Applying the patch from interactivity_score_fix.zip is not as smooth. If system is loaded, audio interrupts and ui feels laggy.
> 
> The smoothest for me has been the old "rdb" branch from the kernel tree. I don't know if that branch is the same as the rdb-r1.zip patch.

Hi @hf29h8sh321 
Yes, it is the same. I have added Cachy-r9 which is the rdb branch cleaned up
https://github.com/hamadmarri/cacule-cpu-scheduler/blob/master/patches/Cachy/v5.9/cachy-5.9-r9.patch

Yes

**Comment by hamadmarri** [comment]
Some results of operarena test on phoronix-test-suite

https://openbenchmarking.org/result/2101084-NI-RDB01063101

**Comment by hamadmarri** [comment]
Compared with BMQ
https://openbenchmarking.org/result/2101110-NI-RDB13468301

**Comment by Salekin-1169** [comment]
> Compared with BMQ
> https://openbenchmarking.org/result/2101110-NI-RDB13468301

Is this version of cachy different from the cacule scheduler ?

**Comment by hamadmarri** [comment]
> > Compared with BMQ
> > https://openbenchmarking.org/result/2101110-NI-RDB13468301
> 
> Is this version of cachy different from the cacule scheduler ?

Hi @Salekin-1169 

Yes, CacULE is slightly different than Cachy.

**Comment by Salekin-1169** [comment]
> > > Compared with BMQ
> > > https://openbenchmarking.org/result/2101110-NI-RDB13468301
> > 
> > 
> > Is this version of cachy different from the cacule scheduler ?
> 
> Hi @Salekin-1169
> 
> Yes, CacULE is slightly different than Cachy.

I see. I had the idea that Cachy was just renamed to CacULE. 
Are you actively developing both schedulers at once? That's impressive.

Just curious why both of them share the same github repo ?

**Comment by Salekin-1169** [comment]
I found your explanation here  
https://forum.xanmod.org/thread-2-page-24.html?highlight=cacule

I'll read more on it. Thanks :bow:

**Comment by hamadmarri** [comment]
> > > > Compared with BMQ
> > > > https://openbenchmarking.org/result/2101110-NI-RDB13468301
> > > 
> > > 
> > > Is this version of cachy different from the cacule scheduler ?
> > 
> > 
> > Hi @Salekin-1169
> > Yes, CacULE is slightly different than Cachy.
> 
> I see. I had the idea that Cachy was just renamed to CacULE.
> Are you actively developing both schedulers at once? That's impressive.
> 
> Just curious why both of them share the same github repo ?

I was planning to only support CacULE instead of Cachy because on my machine CacULE was superior on all tests than Cachy. However, some people believe that Cachy is better, therefore I have to keep cachy alive too. I am planning to make one patch that contains both cachy and cacule.

**Comment by raykzhao** [comment]
Hi @hamadmarri 

I'm wondering if the rdb can also be adapted by CacULE.

**Comment by Salekin-1169** [comment]
Thank you for your hard work. I appreciate it a lot.

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> 
> I'm wondering if the rdb can also be adapted by CacULE.

Hi @raykzhao 

Not yet, I am working on this. The rdb nature depends highly on the HRRN. For CacULE (uses interactivity score) the RDB will be slightly different and I hope it will be as performant as the cachy-rdb. I will share a patch of cacule-rdb for testing soon.

Thank you @raykzhao  for all your help and supports. I am really appreciated.

**Comment by hamadmarri** [comment]
> @hamadmarri Thank you for your hard work. I appreciate it a lot.

No worries @Salekin-1169 

I am thankful too for all your supports and testing.

**Comment by hamadmarri** [comment]
Cacule-rdb patch attached. It doesn't seem as performant as cachy-rdb. Please let me know how it performs.

[cacule-rdb.zip](https://github.com/hamadmarri/cacule-cpu-scheduler/files/5849589/cacule-rdb.zip)

**Comment by raykzhao** [comment]
Hi @hamadmarri 

It seems that the patch is on top of the xanmod-cacule. In order to apply the patch to the vanilla Linux kernel, I need to apply hamadmarri/linux@148c235d6462640686bb98c6a3403700437440fe and cherry-pick hamadmarri/linux@e83a7be10623963f04f2dfedb438faad20a878f9. In addition, I also need to sync the patch without the xanmod `sysctl_sched_latency` tweaks.

With regards to `sysctl_sched_latency`, I am currently using 4ms, since it's the default value of PDS/BMQ timeslice and in zen-kernel CFS (and also the zen-kernel MuQSS `rr_interval` sometime ago). I feel 2ms (current xanmod-cacule default) might be too small for me since I had bad experiences with 2ms timeslice in PDS/BMQ previously. Not sure how this would affect the performance or responsiveness in Cachy/CacULE though.

With the 4ms `sysctl_sched_latency`, Cachy/CacULE both with the rdb feel similarly quite good for me.

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> 
> It seems that the patch is on top of the xanmod-cacule. In order to apply the patch to the vanilla Linux kernel, I need to apply [hamadmarri/linux@148c235](https://github.com/hamadmarri/linux/commit/148c235d6462640686bb98c6a3403700437440fe) and cherry-pick [hamadmarri/linux@e83a7be](https://github.com/hamadmarri/linux/commit/e83a7be10623963f04f2dfedb438faad20a878f9). In addition, I also need to sync the patch without the xanmod `sysctl_sched_latency` tweaks.
> 
> With regards to `sysctl_sched_latency`, I am currently using 4ms, since it's the default value of PDS/BMQ timeslice and in zen-kernel CFS (and also the zen-kernel MuQSS `rr_interval` sometime ago). I feel 2ms (current xanmod-cacule default) might be too small for me since I had bad experiences with 2ms timeslice in PDS/BMQ previously. Not sure how this would affect the performance or responsiveness in Cachy/CacULE though.
> 
> With the 4ms `sysctl_sched_latency`, Cachy/CacULE both with the rdb feel similarly quite good for me.

Hi @raykzhao 

I totally forgot about the `sysctl_sched_latency` changes on xanmod. I believe it affected the rdb implementation on cacule. The reason I tried rdb on xanmod-cacule directly is that based on Alex tests rdb was bad on xanmod. I tested Cachy-rdb on xanomd(without cacule) and it was good same as rdb on vanilla kernel. However, this time rdb on xanmod-cacule wasn't good at all. I think it is due to `sysctl_sched_latency`. Thank you so much for mentioning this. I was wondering why cacule-rdb wasn't good even though the rdb implementation is almost the same to cachy-rdb. I will try to make a cacule-rdb on vanilla kernel, but first I will teak the `sysctl_sched_latency` value and see if I got the same results you got.

Thank you so much :+1:

**Comment by hamadmarri** [comment]
cacule-rdb on vanilla kernel seems better

https://openbenchmarking.org/result/2101233-NI-CACULERDB13

**Comment by raykzhao** [comment]
Hi @hamadmarri 

How does CacULE-rdb compare with Cachy-rdb? It seems that the benchmark score of CacULE-rdb is higher than the score of Cachy-rdb in your previous benchmark. Is that correct? 

As far as CacULE-rdb is better than Cachy-rdb, then I think it makes sense to only maintain CacULE-rdb in the future, if maintaining both Cachy/CacULE has become a burden for you. You may close #19.

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> 
> How does CacULE-rdb compare with Cachy-rdb? It seems that the benchmark score of CacULE-rdb is higher than the score of Cachy-rdb in your previous benchmark. Is that correct?
> 
> As long as CacULE-rdb is better than Cachy-rdb, I think it makes sense to only maintain CacULE-rdb in the future, if maintaining both Cachy/CacULE has become a burden for you. You may close #19.

Hi @raykzhao ,

I reinstalled Opensuse before the last test and didn't compile cachy-rdb. I can't be sure if cacule-rdb is better because Tumbleweed is updated since cachy-rdb test, also I changed FS from btrfs to ext4. I have to compile cachy-rdb on same kernel version and test again.

I think having one patch for both cacule and cachy is possible but need time and also I have to be very careful while joining cachy to cacule in one patch. After combining them, maintaining both in one patch will be easy. I really hope that if anyone still want cachy updated to let me know, or if you all agree that cachy is no more needed also let me know, but it is hard to know that. I don't mind to have both in one patch as you suggested in #19 .

Thank you

**Comment by raykzhao** [comment]
Hi @hamadmarri 

The CacULE-rdb has been so far so good on my machines. 

Two minor things:

1. It is better to also make the `cacule_max_lifetime` tunable via sysctl.
2. It is better to update the documentation and mention the functions that probably would not work correctly with the rdb. Currently I already found that the `schedutil` CPU governor would keep my CPU at the highest frequency most of the time with the rdb. From the source code, I suspect other functions that rely on the load balancing statistics would also be affected.

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> 
> The CacULE-rdb has been so far so good on my machines.
> 
> Two minor things:
> 
>     1. It is better to also make the `cacule_max_lifetime` tunable via sysctl.
> 
>     2. It is better to update the documentation and mention the functions that probably would not work correctly with the rdb. Currently I already found that the `schedutil` CPU governor would keep my CPU at the highest frequency most of the time with the rdb. From the source code, I suspect other functions that rely on the load balancing statistics would also be affected.

Hi @raykzhao 

>It is better to also make the cacule_max_lifetime tunable via sysctl.

I will add the sysctl code for max_lifetime soon, thanks for the reminding :+1:  .

Regarding the second point, I believe there are many features are not working with RDB, such as cpu clamp and others. I am not sure what exactly the affected features, but I'll try my best to mention the features that might be affected by RDB in the documentation.

 Thank you

**Comment by SSalekin** [comment]
I wanted to share my  geekbench results using CacULE (compared to generic). Thanks @hamadmarri for giving us this gem.

![ubuntu](https://user-images.githubusercontent.com/13296638/107154664-2ec83c80-69af-11eb-801a-82775f767df1.png)
![Screenshot from 2021-02-08 01-13-11](https://user-images.githubusercontent.com/13296638/107154672-3f78b280-69af-11eb-9be1-3961ca38f093.png)

**Comment by hamadmarri** [comment]
> I wanted to share my geekbench results using CacULE (compared to generic). Thanks @hamadmarri for giving us this gem.
> # Generic (Ubuntu 20.04.2)
> 
> ![ubuntu](https://user-images.githubusercontent.com/13296638/107154664-2ec83c80-69af-11eb-801a-82775f767df1.png)
> # After installing Xanmod CacULE
> 
> ![Screenshot from 2021-02-08 01-13-11](https://user-images.githubusercontent.com/13296638/107154672-3f78b280-69af-11eb-9be1-3961ca38f093.png)

Hi @SSalekin 

Thank you for sharing this results with us. Most of the performance gained by xanmod patches itself. Thanks to XanMod. The cacule scheduler help on responsiveness and latency of the system.

Thank you

**Comment by mjeveritt** [comment]
Is there any chance this can be backported to 5.4 LTS kernels, or does it depend on features only available in 5.9+ ?
I note from upstream that 5.10 will likely go EOL fairly soon, and I believe 5.8/5.9 are also dead-in-the-water now?!

**Comment by hamadmarri** [comment]
> Is there any chance this can be backported to 5.4 LTS kernels, or does it depend on features only available in 5.9+ ?
> I note from upstream that 5.10 will likely go EOL fairly soon, and I believe 5.8/5.9 are also dead-in-the-water now?!

Hi @mjeveritt 

It doesn't depends on v5.9. It can be ported to 5.4.
I will add 5.4 patch if I had time.

Thank you

**Comment by phush0** [comment]
> Is there any chance this can be backported to 5.4 LTS kernels, or does it depend on features only available in 5.9+ ?
> I note from upstream that 5.10 will likely go EOL fairly soon, and I believe 5.8/5.9 are also dead-in-the-water now?!

5.8 and 5.9 are EOL. 5.10 will be supported till 2022

**Comment by phush0** [comment]
> Hi @hamadmarri
> 
> The CacULE-rdb has been so far so good on my machines.
> 
> Two minor things:
> 
> 1. It is better to also make the `cacule_max_lifetime` tunable via sysctl.
> 2. It is better to update the documentation and mention the functions that probably would not work correctly with the rdb. Currently I already found that the `schedutil` CPU governor would keep my CPU at the highest frequency most of the time with the rdb. From the source code, I suspect other functions that rely on the load balancing statistics would also be affected.

`schedutil` will act same with BMQ/PDS so it is not problem with CacULE alone

**Comment by phush0** [comment]
I am testing CacULE on my old 4 core laptop with 8706G CPU, and what I found till now is that system look very smooth and responsive even during compilation of large project as kernel. What I don't like is that during gaming I see how from time to time one of cores are occupied with kernel load and there is heavy stutter during this time. It is strange because CPU is not loaded 100% but just like ~30 % but then sudden all load disappear from all other cores (they are near 0%) and one core is pegged on almost 100 % just with kernel load. I have linux-tkg compiled with voluntary preempting and cacule-rdb patch.

**Comment by hamadmarri** [comment]
> I am testing CacULE on my old 4 core laptop with 8706G CPU, and what I found till now is that system look very smooth and responsive even during compilation of large project as kernel. What I don't like is that during gaming I see how from time to time one of cores are occupied with kernel load and there is heavy stutter during this time. It is strange because CPU is not loaded 100% but just like ~30 % but then sudden all load disappear from all other cores (they are near 0%) and one core is pegged on almost 100 % just with kernel load. I have linux-tkg compiled with voluntary preempting and cacule-rdb patch.

Hi @phush0 

I won't recommend RDB in case of background load (kernel compilation) - plus gaming. RDB is still experimental load balancer. CacULE (without RDB) is well suited and well tested on XanMod. I am not sure how TKG patches work with CacULE. I suggest that you try CacULE first without RDB. If the problem is still happening then try xanmod-cacule version (without RDB). I found that RDB performs better on the mainline kernel, you could give it a try.

Thank you

**Comment by xuanruiqi** [comment]
Hi Hamad! Wonder if you are already working on CaCULE for 5.11? Thanks!

**Comment by hamadmarri** [comment]
> Hi Hamad! Wonder if you are already working on CaCULE for 5.11? Thanks!

Hi @xuanruiqi 

For the time being, I am not working on cacule. I am looking for a job since about 7 months, no lucks so far.

**Comment by xuanruiqi** [comment]
I see! Since I'm a heavy user of Cacule, I'll perhaps try to port this to 5.11. Hopefully it won't be too hard.

**Comment by raykzhao** [comment]
Hi @hamadmarri @xuanruiqi 

I'm currently using CacULE-rdb with 5.11 kernel. It seems that after merging the upstream commits [3aef1551e942860a3881087171ef0cd45f6ebda7](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/kernel/sched/fair.c?h=v5.11&id=3aef1551e942860a3881087171ef0cd45f6ebda7) and [dc824eb898534cd8e34582874dae3bb7cf2fa008](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/kernel/sched/fair.c?h=v5.11&id=dc824eb898534cd8e34582874dae3bb7cf2fa008) in `select_task_rq_fair`, the CacULE-rdb 5.10 patch can be applied to 5.11.

**Comment by xuanruiqi** [comment]
@raykzhao If you could produce a patch and create a PR that would be awesome!

**Comment by mjeveritt** [comment]
> > Is there any chance this can be backported to 5.4 LTS kernels, or does it depend on features only available in 5.9+ ?
> > I note from upstream that 5.10 will likely go EOL fairly soon, and I believe 5.8/5.9 are also dead-in-the-water now?!
> 
> Hi @mjeveritt
> 
> It doesn't depends on v5.9. It can be ported to 5.4.
> I will add 5.4 patch if I had time.
> 
> Thank you

I have done a trial merge of patches to 5.4 LTS series (using kernel.org git repo, branch 5.4.y).
I will aim to PR this over the weekend.

**Comment by phush0** [comment]
> > I am testing CacULE on my old 4 core laptop with 8706G CPU, and what I found till now is that system look very smooth and responsive even during compilation of large project as kernel. What I don't like is that during gaming I see how from time to time one of cores are occupied with kernel load and there is heavy stutter during this time. It is strange because CPU is not loaded 100% but just like ~30 % but then sudden all load disappear from all other cores (they are near 0%) and one core is pegged on almost 100 % just with kernel load. I have linux-tkg compiled with voluntary preempting and cacule-rdb patch.
> 
> Hi @phush0
> 
> I won't recommend RDB in case of background load (kernel compilation) - plus gaming. RDB is still experimental load balancer. CacULE (without RDB) is well suited and well tested on XanMod. I am not sure how TKG patches work with CacULE. I suggest that you try CacULE first without RDB. If the problem is still happening then try xanmod-cacule version (without RDB). I found that RDB performs better on the mainline kernel, you could give it a try.
> 
> Thank you

Removing RDB fixed my problem. Thank you very much, smoothest system ever.

**Comment by hamadmarri** [comment]
> > > Is there any chance this can be backported to 5.4 LTS kernels, or does it depend on features only available in 5.9+ ?
> > > I note from upstream that 5.10 will likely go EOL fairly soon, and I believe 5.8/5.9 are also dead-in-the-water now?!
> > 
> > 
> > Hi @mjeveritt
> > It doesn't depends on v5.9. It can be ported to 5.4.
> > I will add 5.4 patch if I had time.
> > Thank you
> 
> I have done a trial merge of patches to 5.4 LTS series (using kernel.org git repo, branch 5.4.y).
> I will aim to PR this over the weekend.

Cacule v5.4:
https://github.com/hamadmarri/cacule-cpu-scheduler/tree/master/patches/CacULE/v5.4

Cacule v5.3 + (v5.3 with opensuse Leap 15.2 kernel patches):
https://github.com/hamadmarri/cacule-cpu-scheduler/tree/master/patches/CacULE/v5.3

**Comment by mjeveritt** [comment]
> Cacule v5.4:
> https://github.com/hamadmarri/cacule-cpu-scheduler/tree/master/patches/CacULE/v5.4
> 
> Cacule v5.3 + (v5.3 with opensuse Leap 15.2 kernel patches):
> https://github.com/hamadmarri/cacule-cpu-scheduler/tree/master/patches/CacULE/v5.3

Thanks - will give this a spin! :smiley: :+1:

**Comment by Alt37** [comment]
Hi @hamadmarri 
I have a question about SCHED_AUTOGROUP feature. Is it still needs to be disabled for non-RDB build? Because latest patches point specifically at CACULE_RDB. Even xanmod has it enabled at the moment.
Also 5.10 folder is confusing. You have few patches there. I guess the last one is cacule5.10-rdb.patch but user needs to disable CONFIG_RDB. If so, I guess it's better to delete "cacule5.10-r2.patch" , disable CACULE_RDB by default on "cacule5.10-rdb.patch" and rename it "cacule-5.10.patch" (so it will match 5.3 and 5.4 names).
Thanks!

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> I have a question about CFS Autogroup feature. Is it still needs to be disabled for non-RDB build? Because latest patches point specifically at CACULE_RDB as incompatible option for CGROUP_SCHED & SCHED_AUTOGROUP. Even Xanmod has both options enabled at the moment.
> Also 5.10 folder is confusing. You have few patches there. Reading this topic and looking at dates, I figured out that the last one is "cacule5.10-rdb.patch" but we need to disable CONFIG_RDB. If so, I guess it's better to delete "cacule5.10-r2.patch" , disable CACULE_RDB by default on "cacule5.10-rdb.patch" and rename it to "cacule-5.10.patch" (so it will match 5.3 and 5.4 patches naming).
> Thanks!

Hi @Alt37 

Ok, I will fix the naming issue and disable rdb by default.

For cacule non-rdb, it is full feature support. It works with autogroup and cgroup_sched. My personal preference is to disable both as part of optimization.

Thank you

**Comment by hamadmarri** [comment]
@raykzhao @xuanruiqi 

https://github.com/hamadmarri/cacule-cpu-scheduler/tree/master/patches/CacULE/v5.11

**Comment by hf29h8sh321** [comment]
CacULE (rdb disabled) v5.10 corrupts sound under heavy system load. I will try with rdb enabled.

**Comment by B3HOID** [comment]
Hello, I have some weird issue with CacULE 5.10rdb 5.11 port for Xanmod kernel
        
Playing Overwatch I notice that there is alot of stuttering and overall the FPS is just low (30-40) but that's with ` kernel.sched_interactivity_factor` set to any number that isn't 0. But with it set to 0 the game stops stuttering and the FPS goes back to normal.

I wonder if the ULE interactivity score mechanism design has anything to do with this because it seems that having it set at a particular value besides 0 just hurts my performance.

**Comment by hamadmarri** [comment]
> Hello, I have some weird issue with CacULE 5.10rdb 5.11 port for Xanmod kernel
> 
> Playing Overwatch I notice that there is alot of stuttering and overall the FPS is just low (30-40) but that's with ` kernel.sched_interactivity_factor` set to any number that isn't 0. But with it set to 0 the game stops stuttering and the FPS goes back to normal.
> 
> I wonder if the ULE interactivity score mechanism design has anything to do with this because it seems that having it set at a particular value besides 0 just hurts my performance.

Hi @B3HOID 

Could you please confirm that no background load while playing such as shaders compiling?

**Comment by B3HOID** [comment]
> Could you please confirm that no background load while playing such as shaders compiling?
Actually, this lag occurs when the shaders are compiling. 

But ya3ni it doesn't happen with normal Xanmod that uses CFS, or MuQSS/PDS (some other CPU schedulers I have tried)

**Comment by hamadmarri** [comment]
> > Could you please confirm that no background load while playing such as shaders compiling?
> 
> Actually, this lag occurs when the shaders are compiling.
> But ya3ni it doesn't happen with normal Xanmod that uses CFS, or MuQSS/PDS (some other CPU schedulers I have tried)

Please check the discussion: https://forum.xanmod.org/thread-2-post-7420.html#pid7420

**Comment by hamadmarri** [comment]
> > Could you please confirm that no background load while playing such as shaders compiling?
> 
> Actually, this lag occurs when the shaders are compiling.
> But ya3ni it doesn't happen with normal Xanmod that uses CFS, or MuQSS/PDS (some other CPU schedulers I have tried)

Is harsh_mode enabled?

**Comment by hamadmarri** [comment]
New CacULE logo, Thanks to Alexandre.

![cacule_logo_2021](https://user-images.githubusercontent.com/3954563/110203908-8a3bfc00-7e81-11eb-97ef-99bc6a481f3e.png)

The logo idea is relevant if you think in Russian language

**Comment by phush0** [comment]
I have a hard crash if compile kernel with full preempt
```
мар 05 12:38:10 kernel: general protection fault: 0000 [#1] PREEMPT SMP NOPTI
мар 05 12:38:10 kernel: CPU: 13 PID: 0 Comm: swapper/13 Tainted: P S   U     OE     5.10.20-131-tkg-cfs #1
мар 05 12:38:10 kernel: Hardware name: Razer Blade 15 Studio Edition (Early 2020) - RZ09-033/CH551, BIOS 1.06 09/16/2020
мар 05 12:38:10 kernel: RIP: 0010:usb_hcd_map_urb_for_dma+0xc9/0x500
мар 05 12:38:10 kernel: Code: f6 8b 95 80 00 00 00 f6 c4 02 41 0f 95 c6 41 ff c6 85 d2 75 15 45 31 ed 48 83 c4 08 5b 5d 41 5c 44 89 e8 41 5d 41 5e 41 5f c3 <a8> 04 75 e7 49 83 bc 24 58 02 00 00 00 0f 84 13 01 00 00 41 89 d7
мар 05 12:38:10 kernel: RSP: 0018:ffffada9004c4de0 EFLAGS: 00010202
мар 05 12:38:10 kernel: RAX: 0000000000000200 RBX: ffff9d5320b14940 RCX: ffff9d5303be1ca0
мар 05 12:38:10 kernel: RDX: 0000000000000002 RSI: ffff9d5328857d40 RDI: ffff9d530946e000
мар 05 12:38:10 kernel: mce: [Hardware Error]: CPU 5: Machine Check: 0 Bank 0: 9400004000040150
мар 05 12:38:10 kernel: mce: [Hardware Error]: TSC b5e53af43ca ADDR 1ffff90f68647
```

no problem if I compile with voluntary preempt

**Comment by hamadmarri** [comment]
> 5.10.20-131-tkg-cfs

Hi @phush0 

It seems that you are using tkg patches. Full preempt is working fine on vanilla kernel/xanmod + cacule/+rdb.

> RIP: 0010:usb_hcd_map_urb_for_dma+0xc9/0x500

I don't think that the issue is related to the scheduler.

**Comment by phush0** [comment]
I am not using RDB at all, fact that without full preempt three days later I have no crashes with same peripheral attached. TKG patches are zen patches nothing more

**Comment by hamadmarri** [comment]
Notice that xanmod uses `kernel.sched_harsh_mode_enabled = 1` by default. If you encounter sound/or any interrupts  while system load it is because of the harsh mode, you need to disable it by:
```
sudo sysctl kernel.sched_harsh_mode_enabled=0
```

harsh mode is good to be the default value if you are not compiling stuff. It enhances the responsiveness and sometimes it increases the performance. But you need to pay attention to it in case of experiencing any interrupts while heavy system load.

**Comment by phush0** [comment]
There is a strange effect with CacULE. When I use virtual machine, start is extremely slow, one CPU is bound to kworker-rcu and stay there like 2-3 to 5 minutes, tested with clean build with no other patches effect is same. If I use BMQ - QEMU is better than real pc - windows start bellow 5 seconds. As CacULE is extremely smooth I had to leave it behind, because of this problem. Effect is same with 5.10 and 5.11. I had fair scheduler enabled and autogroup enable but autogroup default is disabled as commented above

**Comment by hamadmarri** [comment]
> There is a strange effect with CacULE. When I use virtual machine, start is extremely slow, one CPU is bound to kworker-rcu and stay there like 2-3 to 5 minutes, tested with clean build with no other patches effect is same. If I use BMQ - QEMU is better than real pc - windows start bellow 5 seconds. As CacULE is extremely smooth I had to leave it behind, because of this problem. Effect is same with 5.10 and 5.11. I had fair scheduler enabled and autogroup enable but autogroup default is disabled as commented above

Harsh_mode was enabled?

**Comment by hamadmarri** [comment]
Closed because the page became large, and hard to load since no pagination.

**Comment by xuanruiqi** [comment]
FYI, there's the new GitHub discussions. Maybe you could try it out?

**Comment by hamadmarri** [comment]
> FYI, there's the new GitHub discussions. Maybe you could try it out?

https://github.com/hamadmarri/cacule-cpu-scheduler/discussions/23

Thank you
